// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkiekvmykegveiiwgkmp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhraWVrdm15a2VndmVpaXdna21wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMTQ4MzMsImV4cCI6MjA3MjU5MDgzM30.l8nF0RFXptf5mL8y-pvzB4pcZK0SZKCTRP9nWvG8-Is";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});